### ISSUE TITLE
I run your program in pycharm ,but appearing any problem

### ISSUE THREAD

**Issue by MMingLeung** [esbullington/flask-bootstrap#8]
I input python run.py in pychram ,it Prompt error like this 
`(venv) C:\Users\Ming\Downloads\flask-bootstrap-master>python run.py
C:\Users\Ming\Downloads\flask-bootstrap-master\app\__init__.py:3: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy import SQLAlchemy
C:\Users\Ming\Downloads\flask-bootstrap-master\app\__init__.py:4: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  from flask.ext.login import LoginManager, current_user
C:\Users\Ming\Downloads\flask-bootstrap-master\app\__init__.py:5: ExtDeprecationWarning: Importing flask.ext.assets is deprecated, use flask_assets instead.
  from flask.ext.assets import Environment, Bundle
C:\Users\Ming\Downloads\flask-bootstrap-master\app\database.py:3: ExtDeprecationWarning: Importing flask.ext.bcrypt is deprecated, use flask_bcrypt instead.
  from flask.ext.bcrypt import Bcrypt
C:\Users\Ming\Downloads\flask-bootstrap-master\app\mod_users\controllers.py:15: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    app = create_app()
  File "C:\Users\Ming\Downloads\flask-bootstrap-master\app\__init__.py", line 21, in create_app
    config = os.path.join(app.root_path, os.environ.get('FLASK_APPLICATION_SETTINGS'))
  File "C:\Users\Ming\Downloads\flask-bootstrap-master\venv\lib\ntpath.py", line 67, in join
    p_drive, p_path = splitdrive(p)
  File "C:\Users\Ming\Downloads\flask-bootstrap-master\venv\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
`
In my limited in Python I can fix it , please help or try to give some ideas how to achieve this

**Comment by esbullington** [comment]
Fixed in latest master
